### PR TITLE
fix local_dev.md file for updated file path & environment variable name

### PR DESCRIPTION
**Pull request by Priyankasaggu11929**
**What this PR does / why we need it**:

The PR makes the following changes:
- delete the interim `cluster-template-byoh.yaml` template file.
- fix the `docs/local_dev.md` file to reflect above file changes, in the following command under the section [`create-docker-hosts`](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/local_dev.md#create-docker-hosts):

  ```
  cat test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-templat.yaml | envsubst | kubectl apply -f -
  ```

~The PR does the following small fixes in the `local_dev.md` document:~
- ~Fix the file path from `test/e2e/data/infrastructure-provider-bringyourownhost/v1beta1/cluster-template-byoh.yaml` to the updated `test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template-byoh.yaml`~
- ~Update the environment variable name from `CONTROL_PLANE_ENDPOINT_IP` to `CONTROL_PLANE_ENDPOINT`~

---

**Additional information:**

Before the changes, while following the steps listed in the document (under [create docker hosts](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/local_dev.md#create-docker-hosts) section), I was getting the following errors:

- First error, due to wrong file path:

      
      ❯ cat test/e2e/data/infrastructure-provider-bringyourownhost/v1beta1/cluster-template-byoh.yaml | envsubst | kubectl apply -f -
      cat: test/e2e/data/infrastructure-provider-bringyourownhost/v1beta1/cluster-template-byoh.yaml: No such file or directory
      error: no objects passed to apply
      

- After fixing the file path, the second error due to wrong environment variable name (or not matching environment variable name available to [fill the value of `host` field in the cluster-template-byoh.yaml](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template-byoh.yaml#L31) file, so ultimately giving empty host value)

```
❯ cat test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template-byoh.yaml | envsubst |  kubectl apply -f -
cluster.cluster.x-k8s.io/test1 unchanged
error: error validating "STDIN": error validating data: ValidationError(ByoCluster.spec.controlPlaneEndpoint): missing required field "host" in io.x-k8s.cluster.infrastructure.v1beta1.ByoCluster.spec.controlPlaneEndpoint; if you choose to ignore these errors, turn validation off with --validate=false
```

### CODE REVIEW

**Comment by dharmjit** [comment]
Hi @Priyankasaggu11929, Thank you for validating the local dev guide and raising this PR. 
We can update the variable name to `CONTROL_PLANE_ENDPOINT_IP` in [cluster-template-byoh](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template-byoh.yaml#L31) as we are using the same name in other templates.

**Comment by anusha94** [comment]
> We can update the variable name to CONTROL_PLANE_ENDPOINT_IP in cluster-template-byoh as we are using the same name in other templates.

Another suggestion: [cluster-template-byoh.yaml](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template-byoh.yaml) was an interim template until [cluster-template.yaml](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template.yaml) was ready. In a subsequent PR, we can delete cluster-template-byoh. So one option would be to use `cluster-template.yaml` for workload cluster creation which I believe is using `CONTROL_PLANE_ENDPOINT_IP` variable

**Comment by Priyankasaggu11929** [comment]
Hello @anusha94 & @dharmjit, thanks so much for the review & feedback.

---

> Another suggestion: cluster-template-byoh.yaml was an interim template until cluster-template.yaml was ready. In a subsequent PR, we can delete cluster-template-byoh. So one option would be to use cluster-template.yaml for workload cluster creation which I believe is using `CONTROL_PLANE_ENDPOINT_IP` variable

One follow up question on above. 

So, IIUC, implementing the above suggestion would mean:
- deleting the `cluster-template-byoh.yaml` file
- And updating the following command in the `local_dev.md` file with a reference to `cluster-template.yaml` in place of `cluster-template-byoh.yaml` ?

```
cat test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template-byoh.yaml | envsubst |  kubectl apply -f -
```

I can make the above changes in this PR only or a subsequent PR is required for the file deletion?

Thank you so much, once again!

**Comment by anusha94** [comment]
@Priyankasaggu11929 
> I can make the above changes in this PR only or a subsequent PR is required for the file deletion?

Yes, your understanding is correct. I don't have any strong opinion. Please go ahead and delete in this PR itself if that's easier.

**Comment by Priyankasaggu11929** [comment]
Thanks @anusha94. I'll update the PR shortly. (apologies for the late response, just involved in my new Hire Corporate Orientation sessions). 🙂

**Comment by Priyankasaggu11929** [comment]
@anusha94, I've updated the PR. Thank you!

**Review by dharmjit — COMMENTED** [review]
Congrats @Priyankasaggu11929  for your first contribution to BYOH. 

LGTM!

**Review by dharmjit — APPROVED** [review]

**Review by anusha94 — APPROVED** [review]

**Pull request merged**
