### PR TITLE
Clusterclass yamls and cluster topology yaml merged

### LINKED ISSUE #643: [WIP] [UX experience] Merge clusterclass and cluster topology yaml into a single file for all packages
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in implementing the feature.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shivi28**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #643 

**Additional information**

**Special notes for your reviewer**

### CODE REVIEW

**Comment by shivi28** [comment]
As per clusterctl logic, if we are putting cluster and clusterclass into the same file, then it would fail if clusterclass object is not already existed in the cluster. So to avoid this failure, we need to keep clusterclass definition in the separate file starting with prefix `clusterclass-`

**Comment by shivi28** [comment]
To closing this PR /close

**Comment by anusha94** [comment]
Do we still need this PR? @shivi28

**Comment by shivi28** [comment]
We can not merge clusterclass and cluster template yamls into a single file because as per clusterctl logic, it first searches in the k8s cluster if we have above referred clusterclass CR already present or not. So if we merge into a single file and tries to apply it, it immediately failed. 
Hence closing this PR
/close

**Pull request closed without merging**
