### PR TITLE
ByoClusterTemplate added for cluster class support

### LINKED ISSUE #536: Add clusterclass template
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add a quickstart cluster class template to create basic clusterclass for BYOH.

Related to #487 

**Anything else you would like to add:**
[Miscellaneous information that will assist in implementing the feature.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shivi28**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #536 

**Additional information**

**Special notes for your reviewer**

### CODE REVIEW

**Comment by shivi28** [comment]
Requesting @dharmjit to kindly review this

**Review by sachinkumarsingh092 — COMMENTED** [review]
Is there no need for any observed state for `ByoClusterTemplate` i.e a `ByoClusterTemplateStatus` for cluster class?

**Comment by shivi28** [comment]
> Is there no need for any observed state for `ByoClusterTemplate` i.e a `ByoClusterTemplateStatus` for cluster class?

Right now there is no benefit of having `status` subresource, but based on use case we can extend it in future.

**Review by dharmjit — APPROVED** [review]
LGTM

**Review by sachinkumarsingh092 — APPROVED** [review]
LGTM

**Pull request merged**
