### PR TITLE
Adding CAPB label in tilt-provider.json

### LINKED ISSUE #722: Failed to intialise management cluster using tilt up
**What steps did you take and what happened:**

 When I try to do tilt up, it fails with below error

```
Initial Build
Loading Tiltfile at: /home/kubo/cluster-api/Tiltfile
local: command -v kubectl || true
local: go env GOOS
 → linux
local: go env GOARCH
 → amd64
local: make -B tilt-prepare && ./hack/tools/bin/tilt-prepare --tools kustomize,envsubst,clusterctl --tilt-settings-file ./tilt-settings.yaml
 → cd hack/tools; go build -tags=tools -o bin/tilt-prepare sigs.k8s.io/cluster-api/hack/tools/tilt-prepare
 → I1008 05:12:35.180657  116714 main.go:120] [main] started
 → I1008 05:12:35.182627  116714 main.go:375] [tools] task group started
 → I1008 05:12:35.182740  116714 main.go:426] [tools/kustomize] task started
 → I1008 05:12:35.182889  116714 main.go:426] [tools/envsubst] task started
 → I1008 05:12:35.200088  116714 main.go:426] [tools/clusterctl] task started
 → I1008 05:12:35.375426  116714 main.go:428] [tools/envsubst] task completed, elapsed: 192.5125ms
 → I1008 05:12:35.428439  116714 main.go:428] [tools/kustomize] task completed, elapsed: 245.670426ms
 → I1008 05:12:40.713230  116714 main.go:428] [tools/clusterctl] task completed, elapsed: 5.51311556s
 → I1008 05:12:40.713278  116714 main.go:377] [tools] task group completed, elapsed: 5.530624798s
 → I1008 05:12:40.713524  116714 main.go:375] [resources] task group started
 → I1008 05:12:40.713571  116714 main.go:426] [resources/cert-manager-cainjector] task started
 → I1008 05:12:40.713589  116714 main.go:426] [resources/cert-manager-webhook] task started
 → I1008 05:12:40.713754  116714 main.go:426] [resources/cert-manager] task started
 → I1008 05:12:40.718896  116714 main.go:426] [resources/cert-manager-controller] task started
 → I1008 05:12:40.719087  116714 main.go:426] [resources/byoh] task started
 → I1008 05:12:40.719553  116714 main.go:426] [resources/kubeadm-control-plane] task started
 → I1008 05:12:40.720059  116714 main.go:426] [resources/core] task started
 → I1008 05:12:40.720939  116714 main.go:426] [resources/kubeadm-bootstrap] task started
 → I1008 05:12:40.721672  116714 main.go:426] [resources/clusterctl.crd] task started
 → I1008 05:12:40.928004  116714 main.go:734] [resources/clusterctl.crd] no changes in the generated yaml
 → I1008 05:12:40.928118  116714 main.go:428] [resources/clusterctl.crd] task completed, elapsed: 206.402882ms
 → I1008 05:12:41.308690  116714 main.go:428] [resources/cert-manager] task completed, elapsed: 594.91779ms
 → I1008 05:12:42.591085  116714 main.go:428] [resources/cert-manager-webhook] task completed, elapsed: 1.877463732s
 → I1008 05:12:42.706687  116714 main.go:428] [resources/cert-manager-controller] task completed, elapsed: 1.98776495s
 → I1008 05:12:42.991434  116714 main.go:428] [resources/cert-manager-cainjector] task completed, elapsed: 2.277842616s
 → I1008 05:12:45.372373  116714 main.go:734] [resources/byoh] no changes in the generated yaml
 → I1008 05:12:45.372511  116714 main.go:428] [resources/byoh] task completed, elapsed: 4.653413109s
 → I1008 05:12:45.411931  116714 main.go:734] [resources/kubeadm-bootstrap] no changes in the generated yaml
 → I1008 05:12:45.412040  116714 main.go:428] [resources/kubeadm-bootstrap] task completed, elapsed: 4.690490956s
 → I1008 05:12:45.484979  116714 main.go:734] [resources/core] no changes in the generated yaml
 → I1008 05:12:45.485004  116714 main.go:428] [resources/core] task completed, elapsed: 4.764931739s
 → I1008 05:12:45.510709  116714 main.go:734] [resources/kubeadm-control-plane] no changes in the generated yaml
 → I1008 05:12:45.510847  116714 main.go:428] [resources/kubeadm-control-plane] task completed, elapsed: 4.791280167s
 → I1008 05:12:45.510894  116714 main.go:377] [resources] task group completed, elapsed: 4.79734877s
 → I1008 05:12:45.510922  116714 main.go:146] [main] completed, elapsed: 10.330109114s
ERROR: Traceback (most recent call last):
  /home/kubo/cluster-api/Tiltfile:570:17: in <toplevel>
  /home/kubo/cluster-api/Tiltfile:368:24: in enable_providers
  /home/kubo/cluster-api/Tiltfile:299:20: in enable_provider
  /home/kubo/cluster-api/Tiltfile:234:14: in build_go_binary
Error: NoneType has no .lower field or method
```

**What did you expect to happen:**
`tilt up` should successfully create management cluster 

**Anything else you would like to add:**

provided `tilt-settings.json` is 
```
default_registry: ""
provider_repos:
- /home/kubo/cluster-api-provider-bringyourownhost
enable_providers:
- byoh
- kubeadm-bootstrap
- kubeadm-control-plane
kustomize_substitutions:
  CLUSTER_TOPOLOGY: "true"
```

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shivi28**
**What this PR does / why we need it**:
Enable users to create management cluster using tilt up

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #722 

**Additional information**
This is done as a follow up of [CAPI](https://github.com/kubernetes-sigs/cluster-api/issues/7201 ) discussion 

**Special notes for your reviewer**

### CODE REVIEW

**Comment by mayur-tolexo** [comment]
LGTM 👍

**Review by shamsher31 — COMMENTED** [review]
@shivi28 Can you please also provide the result of the following command after adding this label?
```
$ tilt up
```

**Comment by shivi28** [comment]
> @shivi28 Can you please also provide the result of the following command after adding this label?
> 
> ```
> $ tilt up
> ```

This will spin up the Management cluster successfully, but if we don't have this label then the error is captured in [this](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/issues/722) issue. 

> #722

**Review by dharmjit — APPROVED** [review]
LGTM!

**Pull request merged**
