### PR TITLE
Update kube-vip to v0.5.0 and go version to v1.18

### LINKED ISSUE #670: Update kube-vip to v0.5.0
Kube-vip v0.5.0 ships with all updated features. We can leverage default interface etc. Probably good to bump to the [v0.5.0 version](https://github.com/kube-vip/kube-vip/releases/tag/v0.5.0)

### PR DESCRIPTION
**Pull request by Madhur97**
**What this PR does / why we need it**:
This PR updates kubevip to v0.5.0
Update to golang to v1.18,  as it is the minimum version supported by kubevip v0.5.0
Updated golangci-lint to v1.46.2 as supported by golang v1.18
Removed a redundant statement in `installer/bundle_downloader_test.go` as suggested by golangci-lint.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #670 

**Special notes for your reviewer**

### CODE REVIEW

**Review by shamsher31 — COMMENTED** [review]
I think the Go upgrade should be separate PR as per the PR title?

**Comment by sachinkumarsingh092** [comment]
@shamsher31 I think it's done due to the minimum go version requirement for kube-vip update being v1.18.

**Review by sachinkumarsingh092 — APPROVED** [review]
lgtm

**Comment by Madhur97** [comment]
> I think the Go upgrade should be separate PR as per the PR title?

As @sachinkumarsingh092 also added in other comment, the Go version is updated because it is needed by kubevip v0.5.0. We can update the PR title to include information about Go version update.

**Review by shubham14bajpai — APPROVED** [review]
LGTM

**Review by anusha94 — APPROVED** [review]
lgtm

**Pull request merged**
