### PR TITLE
Added support for dependabot

### LINKED ISSUE #280: Automate Dependabot security updates
Dependabot alerts security vulnerabilities on the repository. These are mostly vulnerabilities found in the `go.mod` or `go.sum` package versions. These are of various severity levels. Irrespective of that, these vulnerabilities need to fixed at the earliest.

We should automate the vulnerability fixes by allowing dependabot to raise PRs whenever a vulnerability is detected. Follow this guide to enable the same - [Enable Dependabot version updates](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates)

### PR DESCRIPTION
**Pull request by Akasurde**
**What this PR does / why we need it**:
* added support for dependabot

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #280 

**Additional information**

**Special notes for your reviewer**

### CODE REVIEW

**Comment by anusha94** [comment]
@Akasurde 
Thank you for the PR!
Trying to understand what this PR does. Please correct me if I'm wrong.

From the changes, it looks like the GH action will scan weekly for dependabot vulnerabilities in `gomod`? Is it also fixed automatically? As in, will it also raise a PR with the correct dependent versions?

**Comment by Akasurde** [comment]
> From the changes, it looks like the GH action will scan weekly for dependabot vulnerabilities in `gomod`?

yes

 Is it also fixed automatically? As in, will it also raise a PR with the correct dependent versions?

yes, dependabot will weekly check the dependencies and fix them using PR. We would require to review PR and merge it. 
I kept scanning frequency weekly since we will not change dependencies daily. I can change it to daily if you defer to my opinion.

**Comment by anusha94** [comment]
@Akasurde 

Thank you for the explanation! Weekly sounds good to me. Let's get this merged!

**Review by anusha94 — APPROVED** [review]

**Review by dharmjit — APPROVED** [review]
LGTM! Thanks for your contribution @Akasurde 🎉

**Comment by Akasurde** [comment]
@anusha94 @dharmjit Thanks for the review and merge.

**Pull request merged**
