### PR TITLE
Clusterclass quickstart and cluster topology templates for vm and e2e

### LINKED ISSUE #574: Add clusterclass quickstart and cluster topology template for vm and e2e packages
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Related to #487 

**Anything else you would like to add:**
[Miscellaneous information that will assist in implementing the feature.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shivi28**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #574 

**Additional information**
This PR is on hold until #573 gets merged

**Special notes for your reviewer**

### CODE REVIEW

**Review by anusha94 — APPROVED** [review]
lgtm.

**Review by sachinkumarsingh092 — APPROVED** [review]
LGTM

**Review by shamsher31 — APPROVED** [review]
LGTM.

Good to merge as https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/pull/573 is also merged?

**Comment by shivi28** [comment]
> LGTM.
> 
> Good to merge as #573 is also merged?

Thanks @shamsher31 . But currently I am doing testing for this PR on VMs, so once I will be done, then I will remove the `[WIP]` tag and could merge this.

**Comment by shivi28** [comment]
Testing is done on VMs. PR is ready for review

**Review by shamsher31 — COMMENTED** [review]
> But currently I am doing testing for this PR on VMs

@shivi28 Is there another PR to validate that this works on VM?

**Review by shamsher31 — APPROVED** [review]
LGTM 👍

**Review by anusha94 — COMMENTED** [review]
lgtm! Thanks @shivi28 for this PR and testing on VMs :)

**Review by anusha94 — APPROVED** [review]

**Pull request merged**
