### PR TITLE
Fixes format and goimports issues

### LINKED ISSUE #176: Improve golang report card
**What steps did you take and what happened:**
Goreportcard for our repo identified few lint issues. It would be good if we can fix them and improve the score.

**What did you expect to happen:**
More than 95% for all the lint sections

**Anything else you would like to add:**
Report card - https://goreportcard.com/report/github.com/vmware-tanzu/cluster-api-provider-bringyourownhost

### PR DESCRIPTION
**Pull request by pshail**
Signed-off-by: Shailesh Pant <7968042+pshail@users.noreply.github.com>
**What this PR does / why we need it**:
 Fixes format and go import ordering issues
Partially fixes #176

### CODE REVIEW

**Comment by anusha94** [comment]
@pshail Did you run `gofmt` or some other tool while fixing this? If so, do you think it is worth adding to [.golangci.yml](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/.golangci.yml) so that lint check would fail on PR commit?

**Comment by pshail** [comment]
added gofmt, goimports is already there

**Comment by pshail** [comment]
> > /retest
> 
> @pshail we don't have automation for commands :) I have re-triggered the test(from the UI) for now.

Gotcha, would be great if we have this 😄

**Review by anusha94 — APPROVED** [review]
lgtm

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
