### PR TITLE
Add BYOH cluster create sequence diagram

### PR DESCRIPTION
**Pull request by dharmjit**
Co-authored-by: Anusha Hegde <anushah@vmware.com>

**What this PR does / why we need it**:

This PR adds a sequence diagram for `BYOH` cluster creation workflow.

**Which issue(s) this PR fixes** :
Fixes #

### CODE REVIEW

**Comment by huchen2021** [comment]
How about adding "Patch BYOH Provider on Management Cluster"?

**Comment by dharmjit** [comment]
> How about adding "Patch BYOH Provider on Management Cluster"?

@huchen2021 , I do not have strong views on this, but my thoughts were that it's implied that the provider is installed when we say management cluster. I know, currently we have to patch `BYOH` provider separately but that might not be the case going forward.

**Comment by anusha94** [comment]
> How about adding "Patch BYOH Provider on Management Cluster"?

Yes, that's a valid point @huchen2021 
We did discuss about this, but for cluster create, we are assuming the provider is already present on the management cluster - this is something as a preparation step and not really part of "Cluster Create" operation. Makes sense?

**Comment by pshail** [comment]
@dharmjit shall we create an arch.md file where we describe these diagrams and embed the png as well, wdyt?

**Review by jamiemonserrate — APPROVED** [review]
LGTM!

**Comment by dharmjit** [comment]
> @dharmjit shall we create an arch.md file where we describe these diagrams and embed the png as well, wdyt?

Yes, referring to these diagrams in other docs is a good idea for discovery.

**Comment by anusha94** [comment]
> Yes, referring to these diagrams in other docs is a good idea for discovery.

Let's use https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/issues/238 for this.

**Comment by pshail** [comment]
overall /LGTM
@dharmjit minor nits of arrow types for return messages and wherever possible callout sync/async calls

**Comment by pshail** [comment]
@dharmjit let me take care of these nits in #238 , we can merge this 
LGTM!

**Review by pshail — APPROVED** [review]

**Pull request merged**
