### PR TITLE
Add K8sInstallerConfigTemplate CRD

### PR DESCRIPTION
**Pull request by shubham14bajpai**
Signed-off-by: Shubham <shbajpai@vmware.com>

**What this PR does / why we need it**:

This PR adds the k8sInstallerConfigTemplate CRD which is required to generate K8sInstallerConfig CRs for each BYOMachine. There will different templates for controller and worker nodes similar to BYOMachineTemplates and BYOMachine controller will be responsible for creating the K8sInstallerConfig.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Additional information**

**Special notes for your reviewer**

### CODE REVIEW

**Review by mayur-tolexo — DISMISSED** [review]
LGTM

**Review by anusha94 — DISMISSED** [review]

**Review by sachinkumarsingh092 — APPROVED** [review]
LGTM

**Comment by dharmjit** [comment]
Test coverage is shown as decreasing by 3.44%. Could you rebase the PR with main?

**Review by dharmjit — APPROVED** [review]
lgtm

**Review by sachinkumarsingh092 — APPROVED** [review]
LGTM

**Pull request merged**
